version: '3.7'
services:

  caritas-store-traefik-prod:
    image: "traefik:v2.6"
    command:
      - "--providers.docker.constraints=Label(`docker.project`,`caritas-store`)"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--api.insecure=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443/tcp"
      - "8080:8080"
    restart: always
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  caritas-store-api-prod:
    build:
      context: ./caritas-store-api
    image: mastrogiovanni/caritas-store-api:v0.0.3
    restart: always
    depends_on: 
      - caritas-store-traefik-prod
    labels:
      - "docker.project=caritas-store"
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.rule=Host(`${NODE_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    environment:
      - "MONGO_URL=${MONGO_URL}"
      - "DATABASE_NAME=${DATABASE_NAME}"
    command: "npm run start:prod"

  caritas-store-web-prod:
    build:
      context: ./caritas-store-web
    image: mastrogiovanni/caritas-store-web:v0.0.9
    restart: always
    depends_on: 
      - caritas-store-api-prod
    labels:
      - "docker.project=caritas-store"
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.rule=Host(`${NODE_HOST}`) && PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    environment:
      - PORT=3000
      - API_ENDPOINT=/api
    command: "npm run preview"

volumes:
  mongodb_data_container: