version: '3.7'
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db

  traefik:
    image: "traefik:v2.6"
    restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "3000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  api:
    image: mastrogiovanni/caritas-store-api:v0.0.1
    env_file:
      - .env
    restart: always
    depends_on: 
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  web:
    image: mastrogiovanni/caritas-store:v0.0.3
    restart: always
    depends_on: 
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"

volumes:
  mongodb_data_container: