version: '3.7'
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: